### ISSUE TITLE
Opis matematičnega modela

### ISSUE THREAD

**Issue by matijapretnar** [katarinabrilej/Mathematical-models-in-epidemiology#1]
Kot gledava z asistentom ste se dela zelo pridno lotili. Sicer nama projekta ne uspe zagnati, ampak se bova že znašla. Edino, kar morda na tej točki manjka, je `README.md`, v katerem so navodila za zagon in daljši opis teorije (kot sem ravnokar napisal [na učilnici](https://ucilnica.fmf.uni-lj.si/mod/forum/discuss.php?d=15136)).

**Comment by katarinabrilej** [comment]
Najbrž sem spreminjala imena grafov in potem to pozabila spremeniti v Shiny-ju in zato ne dela, bom popravila. Bom dopolnila tudi `README.md`.
